QnV/QnV/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib.auth.views import  password_reset, password_reset_done, password_reset_confirm, password_reset_complete
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls', namespace='login')),
    url(r'^', include('donaciones.urls', namespace='donaciones')),
    url(r'^', include('verificaciones.urls', namespace='verificaciones')),
    url(r'^', include('presentacion.urls', namespace='presentacion')),
    url(r'^reset/password_reset', password_reset,
        {'template_name':'password_reset_form.html',
         'email_template_name': 'password_reset_email.html'},
        name='password_reset'),

    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'password_reset_done.html'},
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'password_reset_confirm.html'},
        name='password_reset_confirm'
       ),

    url(r'^reset/done', password_reset_complete, {'template_name': 'password_reset_complete.html'},
        name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

QnV/presentacion/urls.py
from django.conf.urls import url
from .models import *
from .views import *

urlpatterns = [ 
    url(r'^$', presentacion, name='presentacion'),
    url(r'^municipalidad-de-mendiolaza' , municipalidad, name='municipalidad'),
    url(r'^mensaje', mensaje, name='mensaje'),
    
]

QnV/presentacion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib import admin
# Create your models here.

QnV/presentacion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.template import loader
from django.shortcuts import render
from django.shortcuts import redirect
from .models import *
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.
def presentacion(request):
    template = loader.get_template('presentacion.html')
    context = {}
    return HttpResponse(template.render(context, request))

def municipalidad(request):
    return redirect("http://www.municipiomendiolaza.com.ar/")

def mensaje(request):
    return HttpResponse("<script>alert('Su mensaje fue enviado, gracias por colaborar con QNV'); window.location = '/';</script>")

QnV/presentacion/templates/presentacion.html
{% load static %} {% load staticfiles %}
<html>

<head>
	<!-- Global -->
	<title>QnV - Que No Venza</title>
	<link rel="icon" href="{% static 'logo.png' %}">
	<meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" charset="UTF-8" />

	 <!-- Chrome mobile -->
	<meta name="theme-color" content="#FF5349">

	<!-- CSS -->
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'css/style_pres.css' %}">
	<link rel="stylesheet" href="{% static 'css/_grid.css' %}">
</head>

<body>
<div id="loading"></div>
	<!-- Nav -->

	<section id="section1" class="cd-section fadeonscroll-title">
		<nav>
			<div class="col s12">
				<ul class="center">
					<div class="center">
						<li id="centered"><img class="hide-onload" alt="Icon" src="{% static 'css/img/icon.png' %}"></li>
					</div>
					<li><a href="#section6">CONTACTO</a></li>
					<li><a href="#section4">COMO DONAR</a></li>
					<li class="left-nav"><a href="#section2">QUE SOMOS</a></li>
					<li class="left-nav"><a href="#section3">DONDE DONAR</a></li>
				</ul>
			</div>
		</nav>
		<div class="row">
			<div class="logo-container" style="margin-top:-40px;">
				<div class="content">
					<div class="logo-wrap">
						<div id='logo'></div>
					</div>
				</div>
			</div>
			<div class="qnv-title center fadeonscroll-title">
				<h2 id="title-pro">PROYECTO</h2>
				<h1 id="title-qnv">QUE NO VENZA</h1>
			</div>
			<div class="title-pnl hide-onload">
				<div onclick="window.location.href = '/principal'" class="col s10 offset-s1 m4 offset-m4 l2 offset-l5 center ing-btn">
					<p>INGRESAR</p>
				</div>
				<div class="col s12 position-arrow hide-on-mobile">
					<div class="scroll-down"></div>
				</div>
			</div>
		</div>
	</section>

	<!-- Section -->
	<section id="section2" class="cd-section">
		<div class="row">
			<div class="col s12 intro-pnl">
				<div class="col s12 m10 offset-m1 fadeonscroll">
					<h2 class="center semibold" style="margin-top:60px;">¿QUÉ ES QUE NO VENZA?</h2>
					<div class="col s12 m8 offset-m2 center">
						<p>QNV es un gestor de donaciones web, con una interfaz amigable y simple de usar, que brinda una mano a aquellas personas que no tienen el capital o la capacidad para adquirir medicamentos. Una vez que una donación cumple con los requisitos de un pedido, el dispensario seleccionado funcionara como verificador del medicamento para asegurarse que se encuentre en buen estado y/o no haya sido adulterado.</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Section -->
	<section id="section3" class="cd-section">
		<div class="row">
			<div class="col s12 where-pnl center">
				<h3 class="fadeonscroll wtitle semibold" style="font-size: 2.2rem;">PUNTOS DE DEPÓSITO</h3>
				<div class="col s12 m8 offset-m2 l4 offset-l1 fadeonscroll-left" onclick="window.open('https://goo.gl/maps/CqcoJyqkuDS2')">
					<div id="plate-default" class="plate pointer">Mendiolaza<span>Av. Malvinas Argentinas 170</span></div>
				</div>
				<div class="col s12 m8 offset-m2 l4 offset-l2 fadeonscroll-right rightimg">
					<div id="plate-default-2" class="plate pointer" onclick="window.open('https://goo.gl/maps/Zr2orZWmW9U2')">Talar<span>Av. Martín Tissera 2096</span></div>
				</div>
			</div>
		</div>
	</section>

	<!-- Section -->
	<section id="section4" class="cd-section">
		<div class="row">
			<div class="col s12 how-pnl center">
				<h2 class="fadeonscroll semibold" style="margin-top:60px;">¿CÓMO DONAR O SOLICITAR?</h2>
				<!-- Primer paso -->
				<table>
					<tr>
						<td>
							<div class="hide-on-mobile frame  fadeonscroll-left"><img src="{% static 'css/img/step1.png' %}" height=300 alt="Paso 1" />
							</div>
						</td>
						<td>
							<div class="col m12 right fadeonscroll">
								<h2>Registrate</h2>
								<p>Para poder utilizar QNV es necesario estar registrado en nuestra página web, para hacerlo simplemente completa los datos necesarios para crear un perfil y ya seras parte de la comunidad de QNV.</p>
							</div>
						</td>
					</tr>
				</table>
				<!-- Segundo paso -->
				<table>
					<tr>
						<td>
							<div class="col m12 fadeonscroll">
								<h2>Completa el formulario</h2>
								<p>Si usted desea donar o solicitar un medicamento lo que debe hacer es completar el formulario con los datos del mismo, antes de seguir asegúrese de haber colocado los datos correctamente. Una vez completado se le entregará un código, ya sea de retiro o de donación.</p>
							</div>
						</td>
						<td>
							<div class="hide-on-mobile frame  fadeonscroll-right">
								<img src="{% static 'css/img/step2.png' %}" height=300 alt="Paso 3" />
							</div>
						</td>
					</tr>
				</table>
				<!-- Tercer paso -->
				<table>
					<tr>
						<td>
							<div class="hide-on-mobile frame  fadeonscroll-left">
								<img src="{% static 'css/img/step3.png' %}" height=300 alt="Paso 3" />
							</div>
						</td>
						<td>
							<div class="col m12 right fadeonscroll">
								<h2>Presentate en el dispensario</h2>
								<p>Una vez que tengamos el código en mano, el mismo será enviado por correo electrónico a su cuenta, debemos presentarnos en el dispensario seleccionado, ya sea para retirar nuestro pedido o para entregar una nueva donación. No olvide llevar la receta del médico si es necesario.</p>
							</div>
						</td>
					</tr>
				</table>
			</div>
		</div>
	</section>

	<!-- Section -->
	<section id="section5" class="cd-section">
		<div class="row">
			<div class="final-pnl">
				<div class="fadeonscroll">
					<div class="col s12 center">
						<h2 class="black-text center semibold">¡HORA DE DONAR!</h2>
						<p class="col s10 offset-s1 m8 offset-m2 center">Registrate y empeza a donar/solicitar un medicamento.</p>
					</div>
					<div class="center">
						<a onclick="window.location.href = '/principal'">EMPEZAR</a>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Footer -->
	<footer>
		<div class="row fadeonscroll" id="section6">
			<div class="col s12 l3 offset-l1">
				<h4 class="semibold">Navegacion</h4>
				<ul>
					<li><a href="#section1">Empezar</a></li>
					<li><a href="#section2">Qué somos</a></li>
					<li><a href="#section3">Dónde donar</a></li>
					<li><a href="#section4">Cómo donar</a></li>
				</ul>
			</div>
			<div class="col s12 l4">
				<h4 class="semibold">correo</h4>
				<form action="{% url 'presentacion:mensaje' %}">
					<div class="row">
						<div class="col s6">
							<input class="col s12" placeholder="Nombre" id="exampleEmailInput" type="text" required>
						</div>
						<div class="col s6">
							<input class="col s12" placeholder="Correo electrónico" type="email" required>
						</div>
					</div>
					<div class="col s12">
						<textarea class="col s12" placeholder="Mensaje" id="exampleMessage" required></textarea>
					</div>
					<div class="col s12 center">
						<input value="Enviar" type="submit">
					</div>
				</form>
			</div>
			<div class="col s12 l3">
				<h4 class="semibold">Contacto</h4>
				<ul>
					<li id="comunicate">+54 9 351 3481354</li>
					<li id="comunicate">Av. Malvinas Argentinas 170</li>
					<li id="comunicate">Av. Martín Tissera 2096</li>
					<li id="comunicate" class="noupper">quenovenza@gmail.com</li>
				</ul>
			</div>

			<div class="col s12 m6 offset-m3 center bb-effect">
				<div class="divider"></div><a id="mendiolaza_link" href="municipalidad-de-mendiolaza/" target="_blank">MUNICIPALIDAD DE MENDIOLAZA</a></div>
		</div>
	</footer>

	<!-- Javascripts -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="{% static 'scroll-reveal/scrollreveal.min.js' %}">
	</script>
	<script src="{% static 'hover-image/jquery.plate.js' %}">
	</script>
	<script src="{% static 'lazy-line/jquery.lazylinepainter-1.7.0.min.js' %}">
	</script>
	<script src="{% static 'lazy-line/path.js' %}">
	</script>
	<script>
		$('.titleblock').hide();
		var $logo = $('#logo-lazy');

		$(document).ready(function() {
			//Loading animation
			$("#loading").fadeOut("fast");
			$('.titleblock').show();
			//Intro animation
			$(".hide-onload").hide();
			$(".logo-container").delay(2400).fadeOut("fast");
			$(".hide-onload").delay(2800).fadeIn("slow");
			$("#title-pro").hide().delay(3000).fadeIn("slow");
			$("#title-qnv").hide().delay(3400).fadeIn(1200);
			// Send to the top of page on refresh
			// $(this).scrollTop(0);
			// Image on hover
			$('#plate-default').plate();
			$('#plate-default-2').plate();
			// Animation on scroll
			window.sr = ScrollReveal();
			sr.reveal('.fadeonscroll', {
				duration: 500,
				delay: 300,
			});
			sr.reveal('.fadeonscroll-left', {
				duration: 1200,
				delay: 300,
				origin: 'left',
				distance: '400px',
			});
			sr.reveal('.fadeonscroll-right', {
				duration: 1200,
				delay: 300,
				origin: 'right',
				distance: '400px',
			});
			sr.reveal('.fadeonscroll-title', {
				duration: 1000,
				distance: '0px',
				reset: true,
				viewFactor: 0.7,
				scale: 1,
			});

			/* Smooth anchor transitions on click */
			$("a").on('click', function(event) {
				// Make sure this.hash has a value before overriding default behavior
				if (this.hash !== "") {
					// Prevent default anchor click behavior
					event.preventDefault();
					// Store hash
					var hash = this.hash;
					/* Using jQuery's animate() method to add smooth page scroll
					he optional number (800) specifies the number of milliseconds it takes to scroll to the specified area */
					$('html, body').animate({
						scrollTop: $(hash).offset().top
					}, 1200, function() {
						// Add hash (#) to URL when done scrolling (default click behavior)
						window.hash = "";
					});
				}
			});

		});
	</script>
</body>

</html>